from datetime import datetime
from typing import Dict, Any, List

class ReportService:
    @staticmethod
    def generate_assessment_report(
        cyclone: Dict[str, Any],
        assets: List[Dict[str, Any]],
        critical_count: int,
        high_risk_count: int,
        total_assets: int,
        top_priorities: List[Dict[str, Any]],
        scenario_name: str = "Operational Baseline"
    ) -> Dict[str, Any]:
        """Generates a complete, structured emergency disaster assessment report."""
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        
        # Categorized assets
        hospitals_at_risk = [a for a in assets if a.get("asset_type") == "hospital" and a.get("risk_assessment", {}).get("risk_category") in ("Critical", "High")]
        power_at_risk = [a for a in assets if a.get("asset_type") == "power_station" and a.get("risk_assessment", {}).get("risk_category") in ("Critical", "High")]
        bridges_at_risk = [a for a in assets if a.get("asset_type") == "bridge" and a.get("risk_assessment", {}).get("risk_category") in ("Critical", "High")]
        
        executive_summary = (
            f"Cyclopath AI Decision-Support Assessment for {cyclone.get('name', 'Cyclone Samudra')} ({cyclone.get('category')}). "
            f"Currently situated at Lat {cyclone.get('current_lat')}N, Lng {cyclone.get('current_lng')}E with sustained core winds of "
            f"{cyclone.get('max_wind_speed_kmh')} km/h and central barometric pressure of {cyclone.get('central_pressure_hpa')} hPa. "
            f"Expected landfall corridor: {cyclone.get('estimated_landfall_location')} ({cyclone.get('estimated_landfall_time')}). "
            f"Across {total_assets} monitored critical infrastructure assets in the projected impact swath, {critical_count} assets "
            f"have reached CRITICAL vulnerability (Score > 80/100) and {high_risk_count} have reached HIGH vulnerability (Score 61-80/100). "
            f"Immediate emergency priority should center on hospital power independence, coastal substation isolation, and arterial bridge monitoring."
        )

        critical_assets_table = []
        for a in top_priorities[:8]:
            ra = a.get("risk_assessment", {})
            critical_assets_table.append({
                "asset_id": a.get("asset_id"),
                "name": a.get("name"),
                "type": a.get("asset_type", "").replace("_", " ").title(),
                "district": a.get("district"),
                "score": ra.get("overall_vulnerability_score", 0),
                "risk_category": ra.get("risk_category", "Critical"),
                "primary_driver": ra.get("shap_factors", [{}])[0].get("factor", "Cyclone Exposure") if ra.get("shap_factors") else "Exposure",
                "urgent_action": ra.get("recommended_actions", ["Implement emergency protocol"])[0] if ra.get("recommended_actions") else "Review status"
            })

        evacuation_and_shelter = {
            "monitored_shelters": len([a for a in assets if a.get("asset_type") == "school_shelter"]),
            "shelter_capacity_total": sum(a.get("capacity", 1000) for a in assets if a.get("asset_type") == "school_shelter"),
            "estimated_target_evacuees": 145000,
            "priority_zones": ["Puri Coastal Sector", "Paradip Estuary Zone", "Dhamra Maritime Belt", "Kakatpur Lowlands"]
        }

        disclaimer = (
            "IMPORTANT NOTICE: This emergency assessment report is generated by the Cyclopath AI Decision-Support Platform "
            "(Prototype Version 1.0). Risk estimations and priority rankings are modeled outputs designed to assist emergency "
            "planners in resource allocation. They do NOT replace official India Meteorological Department (IMD) bulletins, "
            "State Disaster Management Authority (SDMA) directives, or certified on-site structural engineering assessments. "
            "All operational actions must be authorized by the competent incident commander."
        )

        return {
            "report_title": f"Cyclopath AI Emergency Infrastructure Vulnerability Report — {cyclone.get('name')}",
            "generated_at": timestamp,
            "scenario": scenario_name,
            "cyclone_snapshot": {
                "name": cyclone.get("name"),
                "category": cyclone.get("category"),
                "wind_speed_kmh": cyclone.get("max_wind_speed_kmh"),
                "pressure_hpa": cyclone.get("central_pressure_hpa"),
                "storm_surge_m": cyclone.get("storm_surge_potential_m"),
                "rainfall_mm": cyclone.get("rainfall_24h_mm"),
                "landfall_location": cyclone.get("estimated_landfall_location"),
                "landfall_time": cyclone.get("estimated_landfall_time")
            },
            "executive_summary": executive_summary,
            "metrics": {
                "total_monitored_assets": total_assets,
                "critical_assets": critical_count,
                "high_risk_assets": high_risk_count,
                "hospitals_at_risk": len(hospitals_at_risk),
                "power_stations_at_risk": len(power_at_risk),
                "bridges_at_risk": len(bridges_at_risk),
                "estimated_exposed_population": 420000
            },
            "critical_assets": critical_assets_table,
            "evacuation_and_shelter": evacuation_and_shelter,
            "data_sources": [
                "IMD Doppler Weather Radar (Paradip & Gopalpur)",
                "ISRO Bhuvan Coastal Inundation Digital Elevation Model",
                "OpenStreetMap Maritime Infrastructure Geodatabase",
                "Odisha State Disaster Management Authority (OSDMA) Public Facility Registry"
            ],
            "disclaimer": disclaimer
        }

report_service = ReportService()
