export class ReportService {
  generateAssessmentReport(
    cyclone: Record<string, any>,
    assets: Array<Record<string, any>>,
    criticalCount: number,
    highRiskCount: number,
    totalAssets: number,
    topPriorities: Array<Record<string, any>>,
    scenarioName = 'Operational Baseline'
  ): Record<string, any> {
    const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC';

    const hospitalsAtRisk = assets.filter(
      (a) => a.asset_type === 'hospital' && ['Critical', 'High'].includes(a.risk_assessment?.risk_category)
    );
    const powerAtRisk = assets.filter(
      (a) => a.asset_type === 'power_station' && ['Critical', 'High'].includes(a.risk_assessment?.risk_category)
    );
    const bridgesAtRisk = assets.filter(
      (a) => a.asset_type === 'bridge' && ['Critical', 'High'].includes(a.risk_assessment?.risk_category)
    );

    const executiveSummary =
      `Cyclopath AI Decision-Support Assessment for ${cyclone.name || 'Cyclone Samudra'} (${cyclone.category}). ` +
      `Currently situated at Lat ${cyclone.current_lat}N, Lng ${cyclone.current_lng}E with sustained core winds of ` +
      `${cyclone.max_wind_speed_kmh} km/h and central barometric pressure of ${cyclone.central_pressure_hpa} hPa. ` +
      `Expected landfall corridor: ${cyclone.estimated_landfall_location} (${cyclone.estimated_landfall_time}). ` +
      `Across ${totalAssets} monitored critical infrastructure assets in the projected impact swath, ${criticalCount} assets ` +
      `have reached CRITICAL vulnerability (Score > 80/100) and ${highRiskCount} have reached HIGH vulnerability (Score 61-80/100). ` +
      `Immediate emergency priority should center on hospital power independence, coastal substation isolation, and arterial bridge monitoring.`;

    const criticalAssetsTable = topPriorities.slice(0, 8).map((a) => {
      const ra = a.risk_assessment || {};
      return {
        asset_id: a.asset_id,
        name: a.name,
        type: (a.asset_type || '').replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase()),
        district: a.district,
        score: ra.overall_vulnerability_score || 0,
        risk_category: ra.risk_category || 'Critical',
        primary_driver: ra.shap_factors?.[0]?.factor || 'Cyclone Exposure',
        urgent_action: ra.recommended_actions?.[0] || 'Review status',
      };
    });

    const shelters = assets.filter((a) => a.asset_type === 'school_shelter');
    const evacuationAndShelter = {
      monitored_shelters: shelters.length,
      shelter_capacity_total: shelters.reduce((acc, curr) => acc + (curr.capacity || 1000), 0),
      estimated_target_evacuees: 145000,
      priority_zones: ['Puri Coastal Sector', 'Paradip Estuary Zone', 'Dhamra Maritime Belt', 'Kakatpur Lowlands'],
    };

    const disclaimer =
      'IMPORTANT NOTICE: This emergency assessment report is generated by the Cyclopath AI Decision-Support Platform ' +
      '(Prototype Version 1.0). Risk estimations and priority rankings are modeled outputs designed to assist emergency ' +
      'planners in resource allocation. They do NOT replace official India Meteorological Department (IMD) bulletins, ' +
      'State Disaster Management Authority (SDMA) directives, or certified on-site structural engineering assessments. ' +
      'All operational actions must be authorized by the competent incident commander.';

    return {
      report_title: `Cyclopath AI Emergency Infrastructure Vulnerability Report — ${cyclone.name}`,
      generated_at: timestamp,
      scenario: scenarioName,
      cyclone_snapshot: {
        name: cyclone.name,
        category: cyclone.category,
        wind_speed_kmh: cyclone.max_wind_speed_kmh,
        pressure_hpa: cyclone.central_pressure_hpa,
        storm_surge_m: cyclone.storm_surge_potential_m,
        rainfall_mm: cyclone.rainfall_24h_mm,
        landfall_location: cyclone.estimated_landfall_location,
        landfall_time: cyclone.estimated_landfall_time,
      },
      executive_summary: executiveSummary,
      metrics: {
        total_monitored_assets: totalAssets,
        critical_assets: criticalCount,
        high_risk_assets: highRiskCount,
        hospitals_at_risk: hospitalsAtRisk.length,
        power_stations_at_risk: powerAtRisk.length,
        bridges_at_risk: bridgesAtRisk.length,
        estimated_exposed_population: 420000,
      },
      critical_assets: criticalAssetsTable,
      evacuation_and_shelter: evacuationAndShelter,
      data_sources: [
        'IMD Doppler Weather Radar (Paradip & Gopalpur)',
        'ISRO Bhuvan Coastal Inundation Digital Elevation Model',
        'OpenStreetMap Maritime Infrastructure Geodatabase',
        'Odisha State Disaster Management Authority (OSDMA) Public Facility Registry',
      ],
      disclaimer,
    };
  }
}

export const reportService = new ReportService();
